spring:
  application:
    name: WuZhu
  main:
    web-application-type: none
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/.wuzhu/h2/wuzhudbjpa;AUTO_SERVER=TRUE
    username: root
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # none, update, create, create-drop
    show-sql: true
    # database: h2
  sql:
    init:
      mode: always
      platform: h2
      #data-locations: classpath:db/data-h2.sql
      schema-locations: classpath:db/schema-h2.sql

mybatis-plus:
  global-config:
    db-config:
      id-type: auto #id生成规则：数据库id自增

coin-market-cap:
  customHeader: X-CMC_PRO_API_KEY
  httpHeader: application/json
  coinMarketCapIDMap: https://pro-api.coinmarketcap.com/v1/cryptocurrency/map
  latestListings: https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest
  quotesLatest: https://pro-api.coinmarketcap.com/v2/cryptocurrency/quotes/latest
  #metadata: https://pro-api.coinmarketcap.com/v1/cryptocurrency/info
  #historicalListings: https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/historical
  #historicalQuotes: https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/historical
  #latestMarketPairs: https://pro-api.coinmarketcap.com/v1/cryptocurrency/market-pairs/latest -
  #latestOHLCV: https://pro-api.coinmarketcap.com/v1/cryptocurrency/ohlcv/latest
  #historicalOHLCV: https://pro-api.coinmarketcap.com/v1/cryptocurrency/ohlcv/historical
  #pricePerformanceStats: https://pro-api.coinmarketcap.com/v1/cryptocurrency/price-performance-stats/latest

feign:
  client:
    config:
      default: # 服务名，填写 default 为所有服务，或者指定某服务，例如：annoroad-beta
        connectTimeout: 10000 # 连接超时，10秒
        readTimeout: 20000 # 读取超时，20秒
  httpclient:
    enabled: false # 关闭 ApacheHttpClient
    max-connections: 50 # 连接池连接最大连接数（缺省值 200）
    time-to-live: 600 # 连接最大闲置时间，单位为秒，600秒==10分钟（缺省值为 900秒==15分钟）
  okhttp:
    enabled: true # 开启 okhttp

proxy:
  #host: 127.0.0.1
  #port: 53214
  domains: pro-api.coinmarketcap.com

