pring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/.wuzhu/h2/wuzhudb;AUTO_SERVER=TRUE
    username: root
    password: root
  sql:
    init:
      mode: always
      platform: h2
      #data-locations: classpath:db/data-h2.sql
      schema-locations: classpath:db/schema-h2.sql
mybatis-plus:
  global-config:
    db-config:
      id-type: auto #id\u751F\u6210\u89C4\u5219\uFF1A\u6570\u636E\u5E93id\u81EA\u589E
coin-market-cap:
  customHeader: X-CMC_PRO_API_KEY
  httpHeader: application/json
  coinMarketCapIDMap: https://pro-api.coinmarketcap.com/v1/cryptocurrency/map
  latestListings: https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest
  quotesLatest: https://pro-api.coinmarketcap.com/v2/cryptocurrency/quotes/latest
  #metadata: https://pro-api.coinmarketcap.com/v1/cryptocurrency/info
  #historicalListings: https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/historical
  #historicalQuotes: https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/historical
  #latestMarketPairs: https://pro-api.coinmarketcap.com/v1/cryptocurrency/market-pairs/latest -
  #latestOHLCV: https://pro-api.coinmarketcap.com/v1/cryptocurrency/ohlcv/latest
  #historicalOHLCV: https://pro-api.coinmarketcap.com/v1/cryptocurrency/ohlcv/historical
  #pricePerformanceStats: https://pro-api.coinmarketcap.com/v1/cryptocurrency/price-performance-stats/latest

feign:
  client:
    config:
      default: # \u670D\u52A1\u540D\uFF0C\u586B\u5199 default \u4E3A\u6240\u6709\u670D\u52A1\uFF0C\u6216\u8005\u6307\u5B9A\u67D0\u670D\u52A1\uFF0C\u4F8B\u5982\uFF1Aannoroad-beta
        connectTimeout: 10000 # \u8FDE\u63A5\u8D85\u65F6\uFF0C10\u79D2
        readTimeout: 20000 # \u8BFB\u53D6\u8D85\u65F6\uFF0C20\u79D2
  httpclient:
    enabled: false # \u5173\u95ED ApacheHttpClient
    max-connections: 50 # \u8FDE\u63A5\u6C60\u8FDE\u63A5\u6700\u5927\u8FDE\u63A5\u6570\uFF08\u7F3A\u7701\u503C 200\uFF09
    time-to-live: 600 # \u8FDE\u63A5\u6700\u5927\u95F2\u7F6E\u65F6\u95F4\uFF0C\u5355\u4F4D\u4E3A\u79D2\uFF0C600\u79D2==10\u5206\u949F\uFF08\u7F3A\u7701\u503C\u4E3A 900\u79D2==15\u5206\u949F\uFF09
  okhttp:
    enabled: true # \u5F00\u542F okhttp

proxy:
  #host: 127.0.0.1
  #port: 53214
  domains: pro-api.coinmarketcap.com

